// ── COLORS — Light, modern RGB palette ───────────────────────
export const C = {
  // Blues — vibrant not dark
  blue:        "#2563eb",
  blueDark:    "#1d4ed8",
  blueLight:   "#eff6ff",
  blueBorder:  "#bfdbfe",
  // Greens
  green:       "#16a34a",
  greenLight:  "#f0fdf4",
  greenBorder: "#bbf7d0",
  greenBadge:  "#dcfce7",
  // Teals
  teal:        "#0d9488",
  tealLight:   "#f0fdfa",
  tealBorder:  "#99f6e4",
  // Ambers / Gold
  amber:       "#d97706",
  amberLight:  "#fffbeb",
  amberBorder: "#fde68a",
  // Purples
  purple:      "#7c3aed",
  purpleLight: "#f5f3ff",
  purpleBorder:"#ddd6fe",
  // Reds
  red:         "#dc2626",
  redLight:    "#fef2f2",
  redBorder:   "#fecaca",
  // Neutrals
  page:        "#f8fafc",
  card:        "#ffffff",
  border:      "#e2e8f0",
  borderLight: "#f1f5f9",
  dark:        "#0f172a",
  mid:         "#475569",
  light:       "#94a3b8",
  lighter:     "#cbd5e1",
  // Keep navy for backwards compat but lighter
  navy:        "#1e40af",
  navyLight:   "#eff6ff",
  navyDark:    "#1e3a8a",
  gold:        "#d97706",
  goldLight:   "#fffbeb",
  goldBorder:  "#fde68a",
};

export const USERS = [
  { id:1, email:"ops@mbmobile.pk",      password:"ops123",   role:"user",       name:"Saif"        },
  { id:2, email:"admin@mbmobile.pk",    password:"admin123", role:"admin",      name:"Bilal"       },
  { id:3, email:"super@clientfirst.com",password:"super123", role:"superAdmin", name:"ClientFirst" },
  { id:4, email:"haroon@mbmobile.pk",   password:"haroon123",role:"user",       name:"Haroon"      },
];

export const MB_CATS = [
  { v:"smartphones",       en:"📱 Smartphones"        },
  { v:"tablets",           en:"📟 Tablets"            },
  { v:"chargers",          en:"🔌 Chargers & Cables"  },
  { v:"headphones",        en:"🎧 Headphones"         },
  { v:"covers",            en:"🛡️ Covers & Cases"     },
  { v:"accessories",       en:"🔧 Accessories"        },
  { v:"power-banks",       en:"🔋 Power Banks"        },
  { v:"screen-protectors", en:"🪟 Screen Protectors"  },
  { v:"memory-cards",      en:"💾 Memory Cards"       },
  { v:"selfie-sticks",     en:"🤳 Selfie Sticks"      },
];

export const PLATFORMS = ["TikTok","Instagram","Facebook","YouTube","WhatsApp","Snapchat","Twitter/X"];
export const WEEKS     = ["Week 1","Week 2","Week 3","Week 4"];

// ── TRANSLATIONS ─────────────────────────────────────────────
export const T = {
  en: {
    dir:"ltr",
    appName:"MB Mobile", appSub:"Operations & Inventory CRM",
    dashboard:"Dashboard", orders:"Orders", operations:"Operations",
    weekly:"Performance", tasks:"Tasks", pipeline:"Pipeline",
    marketing:"Marketing", payments:"Payments", finance:"Finance",
    settings:"Settings", logout:"Sign Out",
    addProduct:"Add Product", productName:"Product Name",
    brand:"Brand", category:"Category", sellPrice:"Sell Price (PKR)",
    wholesale:"Wholesale (PKR)", delivery:"Delivery (PKR)", flyer:"Flyer (PKR)",
    save:"Save", cancel:"Cancel", delete:"Delete",
    totalProducts:"Total Products", pendingReview:"Pending Review",
    deployed:"Deployed", pendingTasks:"Pending Tasks",
    quickActions:"Quick Actions", recentActivity:"Recent Activity",
    newOrder:"New Order", viewTasks:"View Tasks",
    searchProduct:"Search products...",
    step1:"Step 1 — Customer Details", step2:"Step 2 — Select Product",
    step3:"Step 3 — Payment", step4:"Step 4 — Confirm & Dispatch",
    customerName:"Customer Name", area:"Delivery Area", phone:"Phone (optional)",
    qty:"Quantity", paymentMethod:"Payment Method",
    cod:"Cash on Delivery", easypaisa:"Easypaisa", jazzcash:"JazzCash",
    confirmDispatch:"Confirm & Dispatch", orderDispatched:"Order Dispatched!",
    processAnother:"Process Another Order",
    orderHistory:"Order History", revenue:"Revenue", profit:"Profit",
    netProfit:"Net Profit", totalRevenue:"Total Revenue",
    expenses:"Expenses", salaries:"Salaries", adSpend:"Ad Spend",
    loss:"Loss + Returns", orderProfit:"Order Profit",
    superAdmin:"Super Admin", admin:"Admin", user:"User",
    signIn:"Sign In", email:"Email", password:"Password",
    welcome:"Welcome to MB Mobile CRM",
    loginSub:"Sign in to access your dashboard",
    draft:"Draft", reviewed:"Reviewed", deployedLabel:"Deployed",
    approve:"Approve", reject:"Reject", deploy:"Deploy to Website",
    createTask:"Create Task", taskTitle:"Task Title",
    assignTo:"Assign To", dueDate:"Due Date", markDone:"Mark Done",
    note:"Add Note", done:"Done", pending:"Pending",
    noData:"No data yet.", language:"Language",
    reportNow:"Report Now", lossReturn:"Record Loss or Return",
    lossReturnSub:"Report a product loss or customer return",
    weeklyRevenue:"Weekly Revenue", low:"LOW", high:"HIGH",
  },
  ur: {
    dir:"rtl",
    appName:"ایم بی موبائل", appSub:"آپریشنز اور انوینٹری CRM",
    dashboard:"ڈیش بورڈ", orders:"آرڈرز", operations:"آپریشنز",
    weekly:"کارکردگی", tasks:"کام", pipeline:"پائپ لائن",
    marketing:"مارکیٹنگ", payments:"ادائیگیاں", finance:"مالیات",
    settings:"ترتیبات", logout:"سائن آؤٹ",
    addProduct:"پروڈکٹ شامل کریں", productName:"پروڈکٹ نام",
    brand:"برانڈ", category:"زمرہ", sellPrice:"فروخت قیمت",
    wholesale:"تھوک قیمت", delivery:"ڈیلیوری", flyer:"فلائر",
    save:"محفوظ", cancel:"منسوخ", delete:"حذف",
    totalProducts:"کل مصنوعات", pendingReview:"جائزے کے منتظر",
    deployed:"تعینات", pendingTasks:"زیر التواء کام",
    quickActions:"فوری اقدامات", recentActivity:"حالیہ سرگرمی",
    newOrder:"نیا آرڈر", viewTasks:"کام دیکھیں",
    searchProduct:"پروڈکٹ تلاش کریں...",
    step1:"مرحلہ 1 — گاہک کی تفصیلات", step2:"مرحلہ 2 — پروڈکٹ منتخب کریں",
    step3:"مرحلہ 3 — ادائیگی", step4:"مرحلہ 4 — تصدیق اور روانگی",
    customerName:"گاہک کا نام", area:"ڈیلیوری علاقہ", phone:"فون (اختیاری)",
    qty:"تعداد", paymentMethod:"ادائیگی کا طریقہ",
    cod:"کیش آن ڈیلیوری", easypaisa:"ایزی پیسہ", jazzcash:"جاز کیش",
    confirmDispatch:"تصدیق کریں اور روانہ کریں", orderDispatched:"آرڈر روانہ ہو گیا!",
    processAnother:"دوسرا آرڈر", orderHistory:"آرڈر تاریخ",
    revenue:"آمدن", profit:"منافع", netProfit:"خالص منافع",
    totalRevenue:"کل آمدن", expenses:"اخراجات", salaries:"تنخواہیں",
    adSpend:"اشتہاری خرچ", loss:"نقصان", orderProfit:"آرڈر منافع",
    superAdmin:"سپر ایڈمن", admin:"ایڈمن", user:"صارف",
    signIn:"سائن ان", email:"ای میل", password:"پاس ورڈ",
    welcome:"ایم بی موبائل CRM میں خوش آمدید",
    loginSub:"اپنے ڈیش بورڈ تک رسائی کے لیے سائن ان کریں",
    draft:"ڈرافٹ", reviewed:"جائزہ شدہ", deployedLabel:"تعینات",
    approve:"منظور", reject:"مسترد", deploy:"ویب سائٹ پر تعینات",
    createTask:"کام بنائیں", taskTitle:"کام کا عنوان",
    assignTo:"تفویض", dueDate:"آخری تاریخ", markDone:"مکمل کریں",
    note:"نوٹ", done:"مکمل", pending:"زیر التواء",
    noData:"ابھی کوئی ڈیٹا نہیں۔", language:"زبان",
    reportNow:"رپورٹ کریں", lossReturn:"نقصان یا واپسی درج کریں",
    lossReturnSub:"پروڈکٹ نقصان یا گاہک واپسی رپورٹ کریں",
    weeklyRevenue:"ہفتہ وار آمدن", low:"کم", high:"زیادہ",
  },
  ar: {
    dir:"rtl",
    appName:"MB موبايل", appSub:"نظام إدارة العمليات والمخزون",
    dashboard:"لوحة التحكم", orders:"الطلبات", operations:"العمليات",
    weekly:"الأداء", tasks:"المهام", pipeline:"خط الأنابيب",
    marketing:"التسويق", payments:"المدفوعات", finance:"المالية",
    settings:"الإعدادات", logout:"تسجيل الخروج",
    addProduct:"إضافة منتج", productName:"اسم المنتج",
    brand:"العلامة", category:"الفئة", sellPrice:"سعر البيع",
    wholesale:"سعر الجملة", delivery:"التوصيل", flyer:"المنشور",
    save:"حفظ", cancel:"إلغاء", delete:"حذف",
    totalProducts:"إجمالي المنتجات", pendingReview:"بانتظار المراجعة",
    deployed:"منشور", pendingTasks:"مهام معلّقة",
    quickActions:"إجراءات سريعة", recentActivity:"النشاط الأخير",
    newOrder:"طلب جديد", viewTasks:"عرض المهام",
    searchProduct:"ابحث عن منتج...",
    step1:"الخطوة 1 — بيانات العميل", step2:"الخطوة 2 — اختيار المنتج",
    step3:"الخطوة 3 — طريقة الدفع", step4:"الخطوة 4 — تأكيد وشحن",
    customerName:"اسم العميل", area:"منطقة التوصيل", phone:"الهاتف (اختياري)",
    qty:"الكمية", paymentMethod:"طريقة الدفع",
    cod:"الدفع عند الاستلام", easypaisa:"ايزي بيسا", jazzcash:"جاز كاش",
    confirmDispatch:"تأكيد وشحن", orderDispatched:"تم شحن الطلب!",
    processAnother:"طلب آخر", orderHistory:"سجل الطلبات",
    revenue:"الإيرادات", profit:"الربح", netProfit:"صافي الربح",
    totalRevenue:"إجمالي الإيرادات", expenses:"المصروفات",
    salaries:"الرواتب", adSpend:"الإنفاق الإعلاني",
    loss:"الخسائر", orderProfit:"ربح الطلب",
    superAdmin:"مسؤول أعلى", admin:"مسؤول", user:"مستخدم",
    signIn:"تسجيل الدخول", email:"البريد الإلكتروني", password:"كلمة المرور",
    welcome:"مرحباً بك في MB موبايل CRM",
    loginSub:"سجّل الدخول للوصول إلى لوحة التحكم",
    draft:"مسودة", reviewed:"تمت المراجعة", deployedLabel:"منشور",
    approve:"موافقة", reject:"رفض", deploy:"نشر على الموقع",
    createTask:"إنشاء مهمة", taskTitle:"عنوان المهمة",
    assignTo:"إسناد إلى", dueDate:"تاريخ الاستحقاق", markDone:"تم",
    note:"ملاحظة", done:"مكتمل", pending:"قيد الانتظار",
    noData:"لا توجد بيانات بعد.", language:"اللغة",
    reportNow:"إبلاغ", lossReturn:"تسجيل خسارة أو إرجاع",
    lossReturnSub:"أبلغ عن خسارة منتج أو إرجاع عميل",
    weeklyRevenue:"الإيرادات الأسبوعية", low:"منخفض", high:"مرتفع",
  },
};
